//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace I_Logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROIZVODI
    {
        public int Proizvod_id { get; set; }
        public string Ime { get; set; }
        public string Opis { get; set; }
        public string Url { get; set; }
    }
}
